### ISSUE TITLE
Ensure futures and gather them to lock the instances

### ISSUE THREAD

**Issue by akhilman** [joanvila/aioredlock#10]
TODO from source code

https://github.com/joanvila/aioredlock/blob/36207b35a881951227bf81cee8c2287752e14020/aioredlock/redis.py#L51

**Comment by joanvila** [comment]
Thanks for keeping track of this, I'll try to tackle it soon. If you want I'll be happy to receive a PR 🙂

**Comment by akhilman** [comment]
Fixed in [testing](https://github.com/joanvila/aioredlock/tree/testing) branch.

**Comment by akhilman** [comment]
Merged to master.
