### ISSUE TITLE
Memory leaks 

### ISSUE THREAD

**Issue by vasili-ii** [joanvila/aioredlock#101]
Hello,
There is some memory leak in your code in algorithm.py: you don't remove item from _locks dictionary in def unlock.
So if we will use redlock_manager as a global object and will destroy it only on gracefull stop server the _locks dictionary will encrease more and more whithout cleaning it in unlock def as you do it with _watchdog dictionary.

**Comment by gtmanfred** [comment]
please feel free to submit a pr.

**Comment by gtmanfred** [comment]
I released this as part of v0.7.3
