### ISSUE TITLE
Provide a way to extend an already acquired lock for more time

### ISSUE THREAD

**Issue by akhilman** [joanvila/aioredlock#15]
Redis-py's lock has `Lock.extend(time)` method.

Depends from #5

**Comment by joanvila** [comment]
My plan was to tackle all the small bits and pieces missing for the current features and then to take a look at this. Let's leave the issue to not loose track of it and share here any updates on it 🙂

**Comment by akhilman** [comment]
I need this feature for my own project which requires long living locks. So I'll implement it but after merging #7 and solving #5 and #16.

**Comment by akhilman** [comment]
Waiting for #16 and #13 to solve this issue.

Solution will be simple adding one more lua script and method like `lockmanager.extend(lock)` to update lock lifetime by `lock_timeout`.

**Comment by akhilman** [comment]
Fixed in [testing](https://github.com/joanvila/aioredlock/tree/testing) branch.
