### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by akhilman** [joanvila/aioredlock#17]
Lack of logging makes debugging hard, I have to put and remove print's.

Is it OK if i will add logging to this library?

**Comment by akhilman** [comment]
Add logging errors for each instance. For now mistyping redis address gives no clue why lock is not acquired.

**Comment by joanvila** [comment]
Sure, go ahead adding it

**Comment by akhilman** [comment]
Fixed in testing branch.

**Comment by akhilman** [comment]
Merged to master.
