### ISSUE TITLE
Do autopep and isort

### ISSUE THREAD

**Issue by akhilman** [joanvila/aioredlock#18]
I suggest to make code respect peps like line length limit and sort imported libraries.
Fortunetly it can be done just by calling two commands: `isort` and `autopep`.

Is there any reason to not do it?

**Comment by joanvila** [comment]
I was using flake8 to ensure the code follows the peps. Do you think it's not enough?

**Comment by akhilman** [comment]
https://www.python.org/dev/peps/pep-0008/#maximum-line-length
> Maximum Line Length
>
> Limit all lines to a maximum of 79 characters.
>
> For flowing long blocks of text with fewer structural restrictions (docstrings or comments), the line length should be limited to 72 characters.

Also isort does good job to keep imported libraries sorted and grouped

**Comment by akhilman** [comment]
Done in [testing](https://github.com/joanvila/aioredlock/tree/testing) branch

**Comment by akhilman** [comment]
Merged to master.
