### ISSUE TITLE
Make a new release v0.2.0

### ISSUE THREAD

**Issue by akhilman** [joanvila/aioredlock#33]
Please check [testing](https://github.com/joanvila/aioredlock/tree/testing) branch.

As soon as I will be happy with this branch I'll make PR to master. I hope this changes will be shipped as new pip's version.

**Comment by akhilman** [comment]
I did everything I want to do. Please try new version from the [testing](https://github.com/joanvila/aioredlock/tree/testing) branch.

**Comment by marcstreeter** [comment]
hey @akhilman @joanvila anything I can do to get this finalized?

**Comment by akhilman** [comment]
Merged to master.
pip release https://pypi.python.org/pypi?:action=display&name=aioredlock&version=0.2.0
