### ISSUE TITLE
Allow to pass loop to airedlock constructor.

### ISSUE THREAD

**Issue by akhilman** [joanvila/aioredlock#35]
Add an optional loop argument to the aioredlock constructor and pass this value to the aioredis pool constructor.

**Comment by eedalong** [comment]
@akhilman  u undo this feature ? i didnt find anywhere i can pass loop argument to aioredlock constructor?

**Comment by gtmanfred** [comment]
Is this still needed? because right now with asyncio, you can only have one loop per process, so the loop is always the same for `asyncio.get_event_loop()`

**Comment by akhilman** [comment]
Can not actually remember why I need it.
Perhaps only to match with the `aioredis` API:
```python
coroutine aioredis.create_connection(
    address, *,
    db=0, password=None, ssl=None, encoding=None,
    parser=None, loop=None, timeout=None, connection_cls=None
)
```
Closing for now.
