### ISSUE TITLE
A function to return number of active locks

### ISSUE THREAD

**Issue by sprajosh** [joanvila/aioredlock#36]
Would be a nice to have a feature to do that.

**Comment by akhilman** [comment]
> Would be a nice to have a feature to do that.
Could you describe some use cases for this feature?

**Comment by sprajosh** [comment]
This can be used to exit a program when no keys are active.

**Comment by akhilman** [comment]
For now aioredlock almost stateless and even doesn't know if lock is locked until is_locked() is called (see #23). This feature will add a lot of complexity.

For now I'm tracking, extending and finalizing locks in application side, but yes, this code can be moved to aioredlock.

@joanvila what do you think about tracking \ extending locks from aioredlock itself?

**Comment by akhilman** [comment]
Possible implementation:
* Add dictionary to Aioredlock class to track all locks.
* On Aioredlock.lock() add new lock to this dictionary.
* Add internal lock function to Aioredlock class that will periodically:
    * Try to extend all valid locks.
    * Set lock invalid in case of extending fault.
* Remove lock from dictionary when Aioredlock.unlock() is called.

As I said I already have almost all code in my application.

**Comment by akhilman** [comment]
Questions:
* Should this feature be optional?
* If not should we remove extend() method from public interface?

**Comment by gtmanfred** [comment]
Currently the manager keeps track of all of the locks that have been made, we could add a function to check if all the locks are valid, and that would be able to return all currently valid locks which i think would solve this problem?
