### ISSUE TITLE
weird question about aioredis

### ISSUE THREAD

**Issue by marcstreeter** [joanvila/aioredlock#37]
@akhilman I posted a question on aioredis (https://github.com/aio-libs/aioredis/issues/443).
I realize that you're not the maintainer for it but I know that you use aioredis (v1 - which is the one I'm interested in) and so you might be able to give some input to the the migration from v0.3 to v1.0. I also noticed that within aioredlock (which I also use) this bit of code is hit https://github.com/joanvila/aioredlock/blob/master/aioredlock/redis.py#L97-L128 where a pool that is destined for a context manager is returning with `await` when I didn't  see that in any of the literature they had in aioredis.  Would you mind commenting on what's going on there?  During my migration to v1 I first attempted to use the same structure for my async context manager that you use for `connect`, however, for some reason it didn't work (as documented in my question). I ended up going with a different structure that I was hoping that by now I'd have some more input from the aioredis team but they might be on vacation at the moment or tied up else where.

**Comment by akhilman** [comment]
[Here is documentation](https://aioredis.readthedocs.io/en/v1.1.0/migration.html#blocking-operations-and-connection-sharing)

`create_pool` is coroutine, so should be awaited.
[source](https://github.com/aio-libs/aioredis/blob/ea948d0d7047db3315b4fbb9aa66e9ccc7e41522/aioredis/pool.py#L13)
It returns pool instance.


`await pool` gets single connection from pool and makes it exclusive for this coroutine then yields it as _non async_ context manager. This acquired connection will not be accessible from pool until exiting from context manager.
[source](https://github.com/aio-libs/aioredis/blob/ea948d0d7047db3315b4fbb9aa66e9ccc7e41522/aioredis/pool.py#L434)

One problem with exclusive connections is canceling blocking operator.

```python
async def coro():
	with await pool as conn:
		conn.blpop(key)

fut = ensure_future(coro())
await asyncio.sleep(1)
fut.cancel()
```
will log exception.

Seems like aioredis blocking operators can not be really canceled.

**Comment by marcstreeter** [comment]
Many thanks @akhilman for the quick response.   You are awesome!

So I just noticed something, that for some reason hadn't stuck out to me: I'm using


```python
async with pool as connection:
    await connection.get(...)
```

and much of the interaction that I see in the documentation is as well as the aioredlock codebase now that I'm paying attention:

```python

with await pool as connection:
    await connection.get(...)
```

Much of the reason that I use a wrapper is to abstract away library specific interaction (and though common) - I prefer not to change my code base to conform to the `with await` structure.  I went ahead and refactored it like so:

```python
     import aioredis
     from aioredis import ConnectionsPool, Redis
     import config
    
    class RedisWrapper:
        __slots__ = ("_instance", )
        _pool = None
    
        def __init__(self):
            self._instance = None
    
        async def __aenter__(self) -> Redis:
            pool = await self.get_pool()
            self._instance = await pool.acquire()
            return Redis(self._instance)
    
        async def __aexit__(self, exc_type, exc_val, exc_tb):
            pool = await self.get_pool()
            pool.release(self._instance)
            self._instance = None
    
        async def get_pool(self) -> ConnectionsPool:
            if not self._pool:
                self._pool = await aioredis.create_pool(
                    (config.host, config.port),
                    minsize=5,
                    maxsize=10
                )
    
            return self._pool
```

So basically I'm retaining the interaction with 'create_pool' where my context manager is in charge of acquiring/releasing the the connection and I'm also retaining the ability to use the command mixins (as you mentioned -- which is exactly how I was originally interacting with aioredis before the upgrade) by feeding the connection as input into the Redis.

I believe this should work as expected as basically [`create_pool`](https://github.com/aio-libs/aioredis/blob/ea948d0d7047db3315b4fbb9aa66e9ccc7e41522/aioredis/commands/__init__.py#L163) and [`create_redis_pool`](https://github.com/aio-libs/aioredis/blob/ea948d0d7047db3315b4fbb9aa66e9ccc7e41522/aioredis/commands/__init__.py#L182) are having a baby: creating the pool (as done in create `create_redis_pool`) and feeding an acquired connection into `Redis` (as done in `create_pool`).  

Also I noticed something else : looking at the `create_redis_pool` as used in [`aioredlock` here](https://github.com/joanvila/aioredlock/blob/master/aioredlock/redis.py#L122) will get a Redis instance that [it performs`return await self._pool` on](https://github.com/joanvila/aioredlock/blob/master/aioredlock/redis.py#L128)) which in turn calls the (`__await__` function)[https://github.com/aio-libs/aioredis/blob/ea948d0d7047db3315b4fbb9aa66e9ccc7e41522/aioredis/commands/__init__.py#L131-L140] from the `Redis` object.  I would think that it would end up hitting [the section of code](https://github.com/aio-libs/aioredis/blob/ea948d0d7047db3315b4fbb9aa66e9ccc7e41522/aioredis/commands/__init__.py#L135-L139) where it doesn't `release` the connection. That for me was another reason to not use `create_redis_pool`. Maybe it's getting released elsewhere?

You see any draw backs to going this route?
