### ISSUE TITLE
Can't create new connections in pool after .destroy()

### ISSUE THREAD

**Issue by owaaa** [joanvila/aioredlock#38]
We are running into an instance with AWS Elasticache where the IP changes sometimes under a DNS name then aioredis and by extension locks we are using here can never reconnect to that instance. The root issue I think is somewhere in either aioredis, or asyncio resolve and the DNS name on socket connections and determine connection health. However, I can't implement a workaround due to how aioredis currently wraps aioredis.

Connections work fine if a new fresh connection is made. I would like the option (or workaround) to deal with that for my redis locks here.

I believe all that is required is setting `self._pool = None` after clearing the connections but I will try to verify this.

**Comment by owaaa** [comment]
@akhilman I'm still trying to trace down the original issue for IP caching. Basically the redis pool is not recognizing that the IP changes and you get connection exceptions when the IP of the cluster changes (forever, no timeout and doesn't resolve). It appears that resolution in done in asyncio on socket creation which aioredis calls and they have some connection `ping` code but its unclear why it doesn't work. As far as this library though, if I can close connections after a period (w/o destroying the entire aioredis class) and then reconnect it will be an effective workaround for my situation. I've tested #39 and seems to work well.

**Comment by owaaa** [comment]
aioredis advertises automatic reconnect 1.0+ and I think everything is being done correctly here with that regard, its unclear why that doesn't work though.

**Comment by marcstreeter** [comment]
I wonder if this has anything to do with a bit of code I stumbled upon in another question (quoted below):

> Also I noticed something else : looking at the `create_redis_pool` as used in [`aioredlock` here](https://github.com/joanvila/aioredlock/blob/master/aioredlock/redis.py#L122) will get a Redis instance that [it performs`return await self._pool` on](https://github.com/joanvila/aioredlock/blob/master/aioredlock/redis.py#L128)) which in turn calls the [`__await__` function](https://github.com/aio-libs/aioredis/blob/ea948d0d7047db3315b4fbb9aa66e9ccc7e41522/aioredis/commands/__init__.py#L131-L140) from the `Redis` object.  I would think that it would end up hitting [the section of code](https://github.com/aio-libs/aioredis/blob/ea948d0d7047db3315b4fbb9aa66e9ccc7e41522/aioredis/commands/__init__.py#L135-L139) where it doesn't `release` the connection. That for me was another reason to not use `create_redis_pool`. Maybe it's getting released elsewhere?

**Comment by akhilman** [comment]
@owaaa check my PR https://github.com/joanvila/aioredlock/pull/40, is it work for you?

**Comment by akhilman** [comment]
Fixed in master.
