### ISSUE TITLE
Allow to reuse existing AioRedis pool

### ISSUE THREAD

**Issue by alvassin** [joanvila/aioredlock#41]
Is it possible to use existing `Redis` object from aioredis package, but not creating new one?

Currently as i understand i can only pass servers list. But i already have redis in my application and would like to use existing object.

**Comment by akhilman** [comment]
No, it is not possible. And in my opinion will add too much complexity with too small benefits.

**Comment by alvassin** [comment]
How it would be possible to use your library with customized aioredis client?
Why it would add too much complexity? Please explain.

**Comment by akhilman** [comment]
Actually customized aioredis client makes sense. 
Complexity because of we will have to track is redis pool created not by aioredlock and not destroy it at exit.

**Comment by akhilman** [comment]
Pull request is welcome.
