### ISSUE TITLE
Add watchdog feature for redlock

### ISSUE THREAD

**Issue by eedalong** [joanvila/aioredlock#51]
I think it'll be better if watchdog feature is added to redlock so the redlock'life time can be extended automatically and also check the lock's validity automatically if the task thread is still alive. I'll fork the repo and add this feature.

**Comment by akhilman** [comment]
Pull request with implementation is welcome.

**Comment by eedalong** [comment]
@akhilman I've done that bro. Any suggestions are welcomed!

**Comment by akhilman** [comment]
I made a review of your changes.

But I would like to suggest different approach:
* keep `Aioredlock` as is;
* introuduce new class like `AioredlockManager` in new module;
* collect all acquired locks in `AioredlockManager`;
* check all collected locks in loop with interval, extend valid locks and remove all invalid (unlocked) locks.

With this approach user will decide to use `AioredlockManager` or `Aioredlock` directly and source code will be easier to read and maintain.

**Comment by akhilman** [comment]
I'm implementing this future now.

**Comment by akhilman** [comment]
Here is work in progress:
https://github.com/akhilman/aioredlock/blob/pr-autolock/aioredlock/autolock.py

**Comment by eedalong** [comment]
Cool, I read Redisson source code just now because Redisson implemented watchdog for RedLock. And Redisson ONLY assign a watchdog to a lock when user doesnt set leasetime. Its lease_time is -1 by default. And if user dont set it manually, Redisson think the user want to use the lock as long as he needs until he unlock it . In case of user's failure, it choose to extend the lock's lifetime every lockWatchdogTimeout/3 to lockWatchdogTimeout(default 30s)
![捕获](https://user-images.githubusercontent.com/39682259/71763191-eae54700-2f13-11ea-994d-cce30bd84151.PNG)

**Comment by eedalong** [comment]
I think Redisson's way is a pretty good choice. Implement watchdog in AioRedlock, BUT ONLY assgin watchdogs to locks which dont set locked_timeout. In this way, the code will not be unpredictable

**Comment by eedalong** [comment]
The idea of introducing lock_manager class is good, AioRedLock should just be a lock, but now it also plays lock_manager role

**Comment by eedalong** [comment]
I think AioRedlock itself is already a lock manager now. Why do we need a new manager?

**Comment by eedalong** [comment]
lock_time should be each lock's own attribute but now it's the manager's attribute
I think a better way to lock should be lock_manager.lock(resource, lock_timeout), if lock_timeout is -1, then we use internal_lock_timeout(10s by default)

**Comment by akhilman** [comment]
> lock_time should be each lock's own attribute but now it's the
> manager's attribute
> 
> I think a better way to lock should be lock_manager.lock(resource,
> lock_timeout), if lock_timeout is -1, then we use
> internal_lock_timeout(10s by default)
> 
Yes. Passing lock lifetime as optional argument to lock() will be nice.

**Comment by akhilman** [comment]
On Sat, 2020-01-04 at 02:41 -0800, Dalong wrote:
> I think AioRedlock itself is already a lock manager now. Why do we
> need a new manager?
> 

The Aioredlock  do not track anything. It relies on the  state stored
in redis and acts like adapter to manipulate/get data from redis. 
Also I prefer composition of the simple things over wiring up all
together.

**Comment by eedalong** [comment]
I got u, but from my perspective, it acts like a lock_manager, and also in your examples and many places in test code, u call it lock_manager directly 
![捕获](https://user-images.githubusercontent.com/39682259/71764676-da3dcc80-2f25-11ea-9f23-374f8c561afc.PNG)

**Comment by akhilman** [comment]
We have a problem #64
