### ISSUE TITLE
Unset lock if failing to set the lock

### ISSUE THREAD

**Issue by idomozes** [joanvila/aioredlock#59]
According to the RedLock algorithm described in [Redis documentation ](https://redis.io/topics/distlock):

> If the client failed to acquire the lock for some reason (either it was not able to lock N/2+1 instances or the validity time is negative), it will try to unlock all the instances (even the instances it believed it was not able to lock).

This requirement is not satisfied in the `set_lock` function, instead it just raises a LockError.

Desired behaviour: call `unset_lock` with the same identifier when we fail to `set_lock` and then raise a LockError

**Comment by akhilman** [comment]
_set_lock releases lock on any exception: https://github.com/joanvila/aioredlock/blob/65a84bd25e90a6992b0af152a18d182ff90fa123/aioredlock/algorithm.py#L97

**Comment by idomozes** [comment]
Thanks, didn't see that...

**Comment by akhilman** [comment]
You are welcome.
