### ISSUE TITLE
Raise an exception if the lock cannot be obtained for any reason

### ISSUE THREAD

**Issue by joanvila** [joanvila/aioredlock#6]
Right now, each time the client sets the lock it needs to check for `lock.valid`.
Instead of that, the behaviour should be to raise an exception if the lock was not obtained.

**Comment by akhilman** [comment]
I can do.

**Comment by akhilman** [comment]
But threading.Lock.acquire() also returns True and False. In some cases raising exception will make code less readable.
```python
while True:
    lockmanager.lock('resource')
    if not lock.valid:
        continue
    do_something()
    lockmanager.unlock('resource')
```
or
```python
while True:
    try:
        lockmanager.lock('resource')
    except:
        continue
    do_something()
    lockmanager.unlock('resource')
```
It is easy to do but is raising exceptions really better?

**Comment by akhilman** [comment]
Waiting #16 and #15 to solve this one.

**Comment by akhilman** [comment]
We can not raise exception in `Aioredlock.lock()` and return lock same time.
In my opinion raising exception instead of returning invalid lock will make code more complicated.

**Comment by akhilman** [comment]
Fixed in testing branch.

**Comment by akhilman** [comment]
Merged to master.
