### ISSUE TITLE
New release publish to pypi

### ISSUE THREAD

**Issue by deed02392** [joanvila/aioredlock#61]
Latest version on `master` is not published on pypi.

**Comment by akhilman** [comment]
We have some problems in master #68 #65.
Unfortunately I'm not using this library anymore and wont fix it.

**Comment by akhilman** [comment]
Ok. All fixed. Caling @joanvila.

**Comment by deed02392** [comment]
@akhilman thank you! What alternative library are you using now, by the way?

**Comment by akhilman** [comment]
@deed02392 I'm rebuilding my pet project in Rust.

**Comment by joanvila** [comment]
@akhilman do you have a pypi account? I'm willing to give you permissions to do so

**Comment by akhilman** [comment]
No, I have no a pypi account. I'm also about to abandon this project.
I'm sorry.

**Comment by symonsoft** [comment]
Requesting a new release =)

**Comment by gtmanfred** [comment]
I would be willing to help maintain this library! I also need a new release.

Thanks,
Daniel

**Comment by amatai** [comment]
`master` has exactly the feature we are looking for -- timeout per lock instead of global timeout setting. When can be expect 0.4.0 to be pushed to PyPi, will be very very helpful. Is there any I, as a user can do? Thanks in advance.

**Comment by joanvila** [comment]
@gtmanfred I see you have experience with pypi. I've added you as a manager to the project. Feel free to publish new versions. I'm currently disconnected of the project.

**Comment by gtmanfred** [comment]
sounds good, thanks!

**Comment by gtmanfred** [comment]
Would you mind transferring the repository to me so that I can manage the pull requests and issues as well?

Thanks!
Daniel

**Comment by gtmanfred** [comment]
Nevermind, i see the invitation to this repo, that works too!

**Comment by gtmanfred** [comment]
@joanvila hrm, it looks like i do not have the ability to see the settings on the repository, so I cannot add a codecov secret for uploading test coverage reports.

https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets-for-a-repository

Thanks,
Daniel
