### ISSUE TITLE
Call for code reviewers

### ISSUE THREAD

**Issue by akhilman** [joanvila/aioredlock#67]
We need someone to review pull requests to get good quality.
Please leave a comment if you are user of aioredlock.

**Comment by deed02392** [comment]
I am planning to use aioredlock in production. I just need to add a feature that enables me to use my own `AbcPool` derived connection instances

**Comment by akhilman** [comment]
Nice. Feel free to make pull requests.

**Comment by deed02392** [comment]
Will do @akhilman

**Comment by gtmanfred** [comment]
🎉
