### ISSUE TITLE
Install the lock and unlock scripts and switch to EVALSHA

### ISSUE THREAD

**Issue by deed02392** [joanvila/aioredlock#73]
Currently, the algorithm uploads the full lock and unlock Lua script for every execution. Instead, we should try to install the script to the server and execute it using EVALSHA (https://redis.io/commands/evalsha)

**Comment by akhilman** [comment]
It was like that from the begining, but then #43 was merged. Feel free to revert these changes. I'll merge it if you do an additional check in case the server has lost scripts.

**Comment by deed02392** [comment]
Thanks for the tip, I will be adding some check and reinstall logic and make a PR
