### ISSUE TITLE
Add support for connecting to redis using sentinels

### ISSUE THREAD

**Issue by selivan** [joanvila/aioredlock#74]
Connecting via redis sentinels is official way to get HA: https://redis.io/topics/sentinel
Client is programmed with a list of sentinels and it asks first available one, where is redis primary node now.

It would be great if aioredlock could do that. Now the only way to use it reliably with HA redis setup are ugly crutches with haproxy.

**Comment by gtmanfred** [comment]
Here is an example script using the Sentinel to connect to redis masters.

https://github.com/joanvila/aioredlock/blob/master/examples/sentinel.py

**Comment by selivan** [comment]
Thanks, I checked and it works: https://github.com/joanvila/aioredlock/pull/75#issuecomment-657046272
