### ISSUE TITLE
Feature Request: unlock only takes a lock, not a resource name.

### ISSUE THREAD

**Issue by ar4hc** [joanvila/aioredlock#83]
i'd like to be able to `unlock()` using the resource, too. Now  only using the returned lock from `lock()` works.
I'd prefer a solution like `is_locked()` that  takes both kinds of argument.

Background:  

i want to use locks in an REST API, so the caller of unlock() shouldn't (and can't) get the lock object from lock()

**Comment by gtmanfred** [comment]
closed by #84
