### ISSUE TITLE
Is my method of use wrong?

### ISSUE THREAD

**Issue by centosredhat** [joanvila/aioredlock#88]
```
import  asyncio
from aioredlock import Aioredlock, LockError, Sentinel
redis_instances = [('10.5.208.20',6379)]
lock_manager = Aioredlock(redis_instances)
lock_manager.retry_count = 10
async def get_lock():
    try:
        async with await lock_manager.lock("resource_name") as lock:
            print(lock.valid)
    except LockError as e:
        print("Lock not acquired")

async def main():
    tasks = [asyncio.create_task(get_lock()) for i in range(10)]
    await asyncio.wait(tasks)

asyncio.run(main())
```

![image](https://user-images.githubusercontent.com/28090903/114190889-67b86980-997e-11eb-9d2f-003acbe65523.png)

**Comment by gtmanfred** [comment]
Can you provide the entire stack trace in a code block instead of a picture please?
Thanks,
Daniel

**Comment by gtmanfred** [comment]
The problem you are running into is you are using the same LockManager instance across multiple coroutines, which is not thread safe.  You should instantiate a lock for each get_lock() function.  This will create a different redis connection for each lock manager, and you won't be getting the wrong Future back.

```
import  asyncio

from aioredlock import Aioredlock, LockError, Sentinel

redis_instances = [('10.5.208.20', 6379)]
#lock_manager = Aioredlock(redis_instances)
#lock_manager.retry_count = 10


async def get_lock():
    lock_manager = Aioredlock(redis_instances)
    lock_manager.retry_count = 10
    try:
        async with await lock_manager.lock("resource_name") as lock:
            print(lock.valid)
    except LockError as e:
        print("Lock not acquired")


async def main():
    tasks = [asyncio.create_task(get_lock()) for i in range(10)]
    await asyncio.wait(tasks)


asyncio.run(main())
```

**Comment by centosredhat** [comment]
Thanks.

**Comment by centosredhat** [comment]
Sorry I don't know much about thread safety. I myself want to lock and unlock to reuse a connection.

**Comment by gtmanfred** [comment]
Yeah, unfortunately you can't do that with asyncio.  Because when the connection is awaited, it isn't completed, so it is waiting for data to be returned.  So it is in a state that none of the other coroutines can use it to request information from redis.  It will just be getting back the Future from a different coroutine on the loop, which is the error you were seeing.

Similarly, you can't share the same connection across Multiprocessing or Threaded programming.

**Comment by gtmanfred** [comment]
Well, you can reuse the same connection, it just needs to have connection pooling implemented or something that allows the library to create multiple sessions on the same connection, which I don't believe aioredlock implements on the lock_manager. The lock_manager just has one connection, and is not thread safe.

**Comment by centosredhat** [comment]
Thank you very much for your patience.

**Comment by gtmanfred** [comment]
No problem If you want to reuse the connection, you can instantiate a connection pool from aioredis first, and then pass that in as your instance, and that will allow you to reuse the connection pool.

```
import  asyncio

from aioredis import create_redis_pool
from aioredlock import Aioredlock, LockError

redis_instance = ('172.17.0.2', 6379)


class Locker:
    _conn = None
    _manager = None

    def __new__(cls, conn_str):
        cls.conn_str = conn_str
        return super().__new__(cls)

    @classmethod
    async def _get_conn(cls):
        if cls._conn is None:
            cls._conn = await create_redis_pool(cls.conn_str)
        return cls._conn

    async def get_manager(self):
        if self._manager is None:
            lock = await Locker._get_conn()
            self._manager = Aioredlock([await Locker._get_conn()])
            self._manager.retry_count = 10
        return self._manager

    async def get_lock(self):
        manager = await self.get_manager()
        try:
            async with await manager.lock("resource_name") as lock:
                print(lock.valid)
        except LockError as e:
            print("Lock not acquired")


async def main():
    tasks = [asyncio.create_task(Locker(redis_instance).get_lock()) for i in range(10)]
    await asyncio.wait(tasks)


asyncio.run(main())
```
